spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kamikakushi?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 1234
  mail:
    protocol: smtp
    host: smtp.163.com
    port: 25
    username:
    password:
    default-encoding: utf-8
    properties:
      mail:
        debug: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true

